[package]
name = "tari_bulletproofs_plus"
version = "0.2.1"
authors = ["The Tari Development Community"]
edition = "2018"
license = "BSD-3-Clause"
description = "A smaller faster implementation of Bulletproofs"

[dependencies]
blake2 = {version="0.9.1", default-features = false}
byteorder = { version = "1", default-features = false }
curve25519-dalek = {git = "https://github.com/tari-project/curve25519-dalek", tag = "v4.0.1", default-features = false, features = ["serde", "alloc"] }
derive_more = "0.99.17"
digest = { version = "0.9.0", default-features = false }
lazy_static = {version = "1.4.0", default-features = false }
merlin = { version = "3", default-features = false }
# Note: toolchain must be at v1.60+ to support serde v1.0.150+
serde = { version = "1.0.150", default-features = false, optional = true}
sha3 = { version = "0.9.1", default-features = false }
zeroize = { version = "1", default-features = false}
rand_core = { version = "0.5"}
snafu = {version="0.7.4", default-features =false}

[dev-dependencies]
bincode = "1"
criterion = "0.3"
rand = "0.7"

[features]
default = ["u64_backend", "serde"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
simd_backend = ["curve25519-dalek/simd_backend"]

[[bench]]
name = "range_proof"
harness = false
#required-features = ["simd_backend"]

[[bench]]
name = "generators"
harness = false
